version: "3.8"
services:
  mongo:
    image: "mongo:6.0"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  gastrogo-app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data: {}
